version: 2
updates:
- package-ecosystem: gomod
  directories:
  - /
  - /hack/generators/
  schedule:
    interval: daily
  cooldown:
    semver-major-days: 5
    semver-minor-days: 2
    semver-patch-days: 2
    exclude:
    - "github.com/Kong/*"
    - "github.com/kong/*"
  labels:
  - dependencies
  # Create a group of dependencies to be updated together in one pull request
  groups:
     # Specify a name for the group, which will be used in pull request titles and branch names
     k8s.io:
        # Define patterns to include dependencies in the group (based on dependency name)
        applies-to: version-updates # Applies the group rule to version updates
        patterns:
          - "k8s.io/*"
        exclude-patterns:
        - k8s.io/klog/*
        - k8s.io/utils
        - k8s.io/kube-openapi
     # Specify a name for the group, which will be used in pull request titles and branch names.
     actions:
        # Define patterns to include dependencies in the group (based on dependency name).
        applies-to: version-updates # Applies the group rule to version updates.
        patterns:
          - "actions/*"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - github_actions
  cooldown:
    semver-major-days: 5
    semver-minor-days: 2
    semver-patch-days: 2
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  labels:
  - docker
