[settings.github]
github_attestations = false

# NOTE: The reason for tool version being set here and not in .tools-versions.toml
# is that mise requires the version to be specified when using version_prefix
# and we need to set the latter for kustomize because its tags on GitHub are prefixed
# with "kustomize/".

# NOTE renovate's mise manager doesn't want to work with this for some reason
# so we add renovate comments manually here.
# Ref: https://docs.renovatebot.com/modules/manager/mise/

[tools."github:kubernetes-sigs/kustomize"]
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
version = "v5.8.1"
version_prefix = "kustomize/"

[tools."github:Kong/kubernetes-testing-framework"]
# renovate: datasource=github-releases depName=Kong/kubernetes-testing-framework
version = "v0.48.0"
bin = "ktf"

[tools."github:telepresenceio/telepresence"]
# renovate: datasource=github-releases depName=telepresenceio/telepresence
version = "2.27.0"
[tools."github:telepresenceio/telepresence".platforms]
linux-x64 = { asset_pattern = "telepresence-linux-amd64" }
linux-arm64 = { asset_pattern = "telepresence-linux-arm64" }
darwin-arm64 = { asset_pattern = "telepresence-darwin-arm64" }
macos-arm64 = { asset_pattern = "telepresence-darwin-arm64" }

[tools."http:helm"]
# renovate: datasource=github-releases depName=helm/helm
version = "4.1.1"

[tools."http:helm".platforms]
linux-x64 = { url = "https://get.helm.sh/helm-v{version}-linux-amd64.tar.gz" }
linux-arm64 = { url = "https://get.helm.sh/helm-v{version}-linux-arm64.tar.gz" }
macos-arm64 = { url = "https://get.helm.sh/helm-v{version}-darwin-arm64.tar.gz" }

[tools."go:sigs.k8s.io/kube-api-linter/cmd/golangci-lint-kube-api-linter"]
# renovate: datasource=git-refs packageName=https://github.com/kubernetes-sigs/kube-api-linter.git
version = "39e3d06a2850e38a8e9e82918bab14ce84e608de"
