[env]

MISE_DATA_DIR='bin/'

[plugins]

helm = "https://github.com/Antiarchitect/asdf-helm.git#00b6ead39b97536304042241f31242811ca39f74"
govulncheck = "https://github.com/wizzardich/asdf-govulncheck.git#2e3e9ce0edbc6ec89097d221c9a04217bbe1f51b"
markdownlint-cli2 = "https://github.com/paulo-ferraz-oliveira/asdf-markdownlint-cli2.git#6d14d9fb2f6f7572e7cbcbb818da9670ba4bef62"
kubelinter = "https://github.com/the-cashman/asdf-kube-linter.git#14a55249ef69d5fe98b027b89f111aec2c30ee57"
kube-code-generator = "https://github.com/mise-plugins/mise-kube-code-generator.git#e98effe0bda46523b4dee7217767457f7ca13fd4"

# NOTE: The reason for tool version being set here and not in .tools-versions.toml
# is that mise requires the version to be specified when using version_prefix
# and we need to set the latter for kustomize because its tags on GitHub are prefixed
# with "kustomize/".

# NOTE renovate's mise manager doesn't want to work with this for some reason
# so we add renovate comments manually here.
# Ref: https://docs.renovatebot.com/modules/manager/mise/

[tools."github:kubernetes-sigs/kustomize"]
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
version = "v5.8.0"
version_prefix = "kustomize/"

[tools."github:telepresenceio/telepresence"]
# renovate: datasource=github-releases depName=telepresenceio/telepresence
version = "2.25.1"
[tools."github:telepresenceio/telepresence".platforms]
linux-x64 = { asset_pattern = "telepresence-linux-amd64" }
linux-arm64 = { asset_pattern = "telepresence-linux-arm64" }
darwin-arm64 = { asset_pattern = "telepresence-darwin-arm64" }
macos-arm64 = { asset_pattern = "telepresence-darwin-arm64" }
