apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    name: gateway-operator-webhook
  name: gateway-operator-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-operator-admission
subjects:
- kind: ServiceAccount
  name: gateway-operator-admission
  namespace: kong-system
