apiGroupVersions:
  konnect.konghq.com/v1alpha1:
    types:
      - path: /v3/portals
        cel:
          name:
            _validations:
              - "+kubebuilder:validation:XValidation:rule=\"self == oldSelf\",message=\"name is immutable\""
        ops:
          create:
            path: github.com/Kong/sdk-konnect-go/models/components.CreatePortal
          update:
            path: github.com/Kong/sdk-konnect-go/models/components.UpdatePortal
      - path: /v3/portals/{portalId}/teams
      - path: /v3/portals/{portalId}/custom-domain
      - path: /v3/identity-providers
      - path: /v2/dcr-providers
      - path: /v3/portals/{portalId}/teams/{teamId}/developers
