apiVersion: gateway-operator.konghq.com/v1alpha1
kind: ControlPlane
metadata:
  name: controlplane-example
spec:
  dataplane: dataplane-example
  gatewayClass: kong
  deployment:
    pods:
      containerImage: kong/kubernetes-ingress-controller
      version: "2.10"
      labels:
        controlplane-pod-label: example
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "1000m"
