apiVersion: gateway-operator.konghq.com/v1alpha1
kind: ControlPlane
metadata:
  name: controlplane-example
spec:
  dataplane: dataplane-example
  gatewayClass: kong
  deployment:
    podTemplateSpec:
      metadata:
        labels:
          controlplane-pod-label: example
      spec:
        containers:
        - name: controller
          image: kong/kubernetes-ingress-controller:2.10
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
