# Ensure that you create a secret containing your cluster certificate before applying this
# kubectl create secret tls konnect-client-tls -n kong --cert=./tls.crt --key=./tls.key
apiVersion: gateway-operator.konghq.com/v1alpha1
kind: DataPlane
metadata:
  name: dataplane-example
  namespace: kong
spec:
  deployment:
    pods:
      containerImage: kong/kong-gateway
      version: "3.3"
      volumes:
        - name: konnect-client-tls
          secret:
            secretName: konnect-client-tls
      volumeMounts:
        - name: konnect-client-tls
          mountPath: /etc/secrets/kong-cluster-cert/
      env:
        - name: KONG_ROLE
          value: data_plane
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_CLUSTER_MTLS
          value: pki
        - name: KONG_CLUSTER_CONTROL_PLANE
          value: YOUR_CP_ID.us.cp0.konghq.com:443
        - name: KONG_CLUSTER_SERVER_NAME
          value: YOUR_CP_ID.us.cp0.konghq.com
        - name: KONG_CLUSTER_TELEMETRY_ENDPOINT
          value: YOUR_CP_ID.us.tp0.konghq.com:443
        - name: KONG_CLUSTER_TELEMETRY_SERVER_NAME
          value: YOUR_CP_ID.us.tp0.konghq.com
        - name: KONG_CLUSTER_CERT
          value: /etc/secrets/kong-cluster-cert/tls.crt
        - name: KONG_CLUSTER_CERT_KEY
          value: /etc/secrets/kong-cluster-cert/tls.key
        - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
          value: system
        - name: KONG_KONNECT_MODE
          value: "on"
        - name: KONG_VITALS
          value: "off"
