# Ensure that you create a secret containing your cluster certificate before applying this
# kubectl create secret tls konnect-client-tls -n kong --cert=./tls.crt --key=./tls.key
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: konnect-client-tls
# type: kubernetes.io/tls
# stringData:
#   tls.crt: |
#     -----BEGIN CERTIFICATE-----
#     MIIDhDCCAm6gAwIBAgIBATALBgkqhkiG9w0BAQ0wLDEqMAkGA1UEBhMCVVMwHQYD...
#     zy5lW2IG5AjNDV8VBCthVj5j1UENTVi4rLhu8j/kfb9gNhvqaN8UcA==
#     -----END CERTIFICATE-----
#   tls.key: |
#     -----BEGIN PRIVATE KEY-----
#     MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChCERwsegdWSnS...
#     WSK9kndNKpFI4vPvuw6j2JJl
#     -----END PRIVATE KEY-----
# ---
apiVersion: gateway-operator.konghq.com/v1beta1
kind: DataPlane
metadata:
  name: konnect-example
spec:
  deployment:
    replicas: 3
    podTemplateSpec:
      metadata:
        labels:
          dataplane-pod-label: example
        annotations:
          dataplane-pod-annotation: example
      spec:
        containers:
        - name: proxy
          image: kong/kong-gateway:3.4
          env:
            - name: KONG_ROLE
              value: data_plane
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_CLUSTER_MTLS
              value: pki
            - name: KONG_CLUSTER_CONTROL_PLANE
              value: <YOUR_CP_ID>.cp0.konghq.tech:443
            - name: KONG_CLUSTER_SERVER_NAME
              value: <YOUR_CP_ID>.cp0.konghq.tech
            - name: KONG_CLUSTER_TELEMETRY_ENDPOINT
              value: <YOUR_CP_ID>.tp0.konghq.tech:443
            - name: KONG_CLUSTER_TELEMETRY_SERVER_NAME
              value: <YOUR_CP_ID>.tp0.konghq.tech
            - name: KONG_CLUSTER_CERT
              value: /etc/secrets/kong-cluster-cert/tls.crt
            - name: KONG_CLUSTER_CERT_KEY
              value: /etc/secrets/kong-cluster-cert/tls.key
            - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
              value: system
            - name: KONG_KONNECT_MODE
              value: "on"
            - name: KONG_VITALS
              value: "off"
            - name: KONG_CLUSTER_DP_LABELS
              value: "type:k8s"
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 1
          volumeMounts:
          # We need to specify the cluster-certificate volume-mount because otherwise
          # strategic merge patch would merge its entry with provided
          # konnect-client-tls volume mount.
          - name: cluster-certificate
            mountPath: /var/cluster-certificate
          - name: konnect-client-tls
            mountPath: /etc/secrets/kong-cluster-cert/
            readOnly: true
        volumes:
        - name: cluster-certificate
        - name: konnect-client-tls
          secret:
            secretName: konnect-client-tls
            # This is necessary because we're not able to correctly
            # handle API fields that are filled with defaults by the
            # API server.
            # https://github.com/Kong/gateway-operator/issues/904
            defaultMode: 420
