apiVersion: v1
kind: Secret
metadata:
  labels:
    konghq.com/secret: "true"
  name: test-tls-secret
  namespace: default
type: kubernetes.io/tls
stringData:
  tls.crt: cert_data
  tls.key: key_data
---
apiVersion: konnect.konghq.com/v1alpha1
kind: KonnectAPIAuthConfiguration
metadata:
  name: kong-konnect-api-auth
  namespace: default
spec:
  serverURL: eu.api.konghq.tech
  token: kpat_XXXXXXXXXXXXXXXXXXX
  type: token
---
apiVersion: gateway-operator.konghq.com/v2beta1
kind: GatewayConfiguration
metadata:
  name: kong-gateway-configuration
  namespace: default
spec:
  dataPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
            - image: kong/kong-gateway:3.12
              name: proxy
  konnect:
    authRef:
      name: kong-konnect-api-auth
    source: Origin
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong-gateway-class
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
    group: gateway-operator.konghq.com
    kind: GatewayConfiguration
    name: kong-gateway-configuration
    namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong-gateway
  namespace: default
spec:
  gatewayClassName: kong-gateway-class
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: example.localdomain.dev
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: test-tls-secret
            namespace: default
        mode: Terminate
