# TODO: Enable conversion webhooks for test suites:
# https://github.com/Kong/kong-operator/issues/1986
# kind: GatewayConfiguration
# apiVersion: gateway-operator.konghq.com/v1beta1
# metadata:
#   name: kong
#   namespace: default
# spec:
#   dataPlaneOptions:
#     deployment:
#       scaling:
#         horizontal:
#           minReplicas: 2
#           maxReplicas: 10
#           metrics:
#           - type: Resource
#             resource:
#               name: cpu
#               target:
#                 type: Utilization
#                 averageUtilization: 50
#           behavior:
#             scaleDown:
#               stabilizationWindowSeconds: 1
#               policies:
#               - type: Percent
#                 value: 100
#                 periodSeconds: 2
#             scaleUp:
#               stabilizationWindowSeconds: 1
#               policies:
#               - type: Percent
#                 value: 100
#                 periodSeconds: 2
#               - type: Pods
#                 value: 5
#                 periodSeconds: 2
#               selectPolicy: Max
#       podTemplateSpec:
#         spec:
#           containers:
#           - name: proxy
#             # renovate: datasource=docker versioning=docker
#             image: kong/kong-gateway:3.13
#             readinessProbe:
#               initialDelaySeconds: 1
#               periodSeconds: 1
#   controlPlaneOptions:
#     deployment:
#       podTemplateSpec:
#         spec:
#           containers:
#           - name: controller
#             env:
#             - name: CONTROLLER_LOG_LEVEL
#               value: debug
# ---
# kind: GatewayClass
# apiVersion: gateway.networking.k8s.io/v1
# metadata:
#   name: kong
# spec:
#   controllerName: konghq.com/gateway-operator
#   parametersRef:
#     group: gateway-operator.konghq.com
#     kind: GatewayConfiguration
#     name: kong
#     namespace: default
# ---
# kind: Gateway
# apiVersion: gateway.networking.k8s.io/v1
# metadata:
#   name: kong
#   namespace: default
# spec:
#   gatewayClassName: kong
#   listeners:
#   - name: http
#     protocol: HTTP
#     port: 80
