---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubernetes-configuration.konghq.com/channels: kong-operator
    kubernetes-configuration.konghq.com/version: v2.1.0
  name: mcpservers.konnect.konghq.com
spec:
  group: konnect.konghq.com
  names:
    categories:
    - kong
    - konnect
    kind: MCPServer
    listKind: MCPServerList
    plural: mcpservers
    singular: mcpserver
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MCPServer is the Schema for the MCPServer API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: MCPServerSpec is the specification of the MCPServer resource.
            properties:
              mirror:
                description: |-
                  Mirror is the Konnect Mirror configuration.
                  It is only applicable for ControlPlanes that are created as Mirrors.
                properties:
                  konnect:
                    description: |-
                      Konnect contains the KonnectID of the KonnectGatewayControlPlane that
                      is mirrored.
                    properties:
                      id:
                        description: |-
                          ID is the ID of the Konnect entity. It can be set only in case
                          the ControlPlane type is Mirror.
                        maxLength: 36
                        pattern: ^[0-9a-f]{8}(?:\-[0-9a-f]{4}){3}-[0-9a-f]{12}$
                        type: string
                    required:
                    - id
                    type: object
                required:
                - konnect
                type: object
              source:
                default: Mirror
                description: Source represents the source type of the Konnect entity.
                enum:
                - Mirror
                type: string
            type: object
        type: object
    served: true
    storage: true
