---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubernetes-configuration.konghq.com/channels: kong-operator
    kubernetes-configuration.konghq.com/version: v2.1.0
  name: portals.konnect.konghq.com
spec:
  group: konnect.konghq.com
  names:
    kind: Portal
    listKind: PortalList
    plural: portals
    singular: portal
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Konnect ID
      jsonPath: .status.id
      name: ID
      type: string
    - description: The Resource is Programmed on Konnect
      jsonPath: .status.conditions[?(@.type=='Programmed')].status
      name: Programmed
      type: string
    - description: Konnect Organization ID this resource belongs to.
      jsonPath: .status.organizationID
      name: OrgID
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Portal is the Schema for the portals API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PortalSpec defines the desired state of Portal.
            properties:
              authentication_enabled:
                default: true
                description: |-
                  Whether the portal supports developer authentication.
                  If disabled, developers cannot register for accounts or create applications.
                type: boolean
              auto_approve_applications:
                default: false
                description: |-
                  Whether requests from applications to register for APIs will be
                  automatically approved, or if they will be set to pending until approved by
                  an admin.
                type: boolean
              auto_approve_developers:
                default: false
                description: |-
                  Whether developer account registrations will be automatically approved, or
                  if they will be set to pending until approved by an admin.
                type: boolean
              default_api_visibility:
                description: |-
                  The default visibility of APIs in the portal.
                  If set to `public`, newly published APIs are visible to unauthenticated
                  developers.
                  If set to `private`, newly published APIs are hidden from unauthenticated
                  developers.
                enum:
                - public
                - private
                maxLength: 256
                type: string
              default_application_auth_strategy_id_ref:
                description: |-
                  The default authentication strategy for APIs published to the portal.
                  Newly published APIs will use this authentication strategy unless overridden
                  during publication.
                  If set to `null`, API publications will not use an authentication strategy
                  unless set during publication.
                properties:
                  name:
                    description: Name is the name of the referenced object
                    maxLength: 253
                    minLength: 1
                    type: string
                required:
                - name
                type: object
              default_page_visibility:
                description: |-
                  The default visibility of pages in the portal.
                  If set to `public`, newly created pages are visible to unauthenticated
                  developers.
                  If set to `private`, newly created pages are hidden from unauthenticated
                  developers.
                enum:
                - public
                - private
                maxLength: 256
                type: string
              description:
                description: A description of the portal.
                maxLength: 512
                type: string
              display_name:
                description: |-
                  The display name of the portal.
                  This value will be the portal's `name` in Portal API.
                maxLength: 255
                minLength: 1
                type: string
              labels:
                additionalProperties:
                  type: string
                description: |-
                  Labels store metadata of an entity that can be used for filtering an entity
                  list or for searching across entity types.

                  Labels are intended to store **INTERNAL** metadata.

                  Keys must be of length 1-63 characters, and cannot start with "kong",
                  "konnect", "mesh", "kic", or "_".
                type: object
              name:
                description: |-
                  The name of the portal, used to distinguish it from other portals.
                  Name must be unique.
                maxLength: 255
                minLength: 1
                type: string
                x-kubernetes-validations:
                - message: name is immutable
                  rule: self == oldSelf
              rbac_enabled:
                default: false
                description: |-
                  Whether the portal resources are protected by Role Based Access Control
                  (RBAC).
                  If enabled, developers view or register for APIs until unless assigned to
                  teams with access to view and consume specific APIs.
                  Authentication must be enabled to use RBAC.
                type: boolean
            required:
            - name
            type: object
          status:
            description: PortalStatus defines the observed state of Portal.
            properties:
              conditions:
                description: Conditions represent the current state of the resource.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                maxItems: 8
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              id:
                description: |-
                  ID is the unique identifier of the Konnect entity as assigned by Konnect API.
                  If it's unset (empty string), it means the Konnect entity hasn't been created yet.
                maxLength: 256
                type: string
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                format: int64
                type: integer
              organizationID:
                description: OrgID is ID of Konnect Org that this entity has been
                  created in.
                maxLength: 256
                type: string
              serverURL:
                description: ServerURL is the URL of the Konnect server in which the
                  entity exists.
                maxLength: 512
                type: string
            type: object
        required:
        - metadata
        type: object
    served: true
    storage: true
    subresources:
      status: {}
