---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.2
  name: dataplanekonnectextensions.gateway-operator.konghq.com
spec:
  group: gateway-operator.konghq.com
  names:
    categories:
    - kong
    - all
    kind: DataPlaneKonnectExtension
    listKind: DataPlaneKonnectExtensionList
    plural: dataplanekonnectextensions
    singular: dataplanekonnectextension
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |-
          DataPlaneKonnectExtension is the Schema for the dataplanekonnectextension API,
          and is intended to be referenced as extension by the dataplane API.
          If a DataPlane successfully refers a DataPlaneKonnectExtension, the DataPlane
          deployment spec gets customized to include the konnect-related configuration.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Spec is the specification of the DataPlaneKonnectExtension
              resource.
            properties:
              clusterCertificateSecretName:
                description: ClusterCertificateSecretName is a name of the Secret
                  containing the Konnect Control Plane's cluster certificate.
                type: string
              clusterDataPlaneLabels:
                additionalProperties:
                  type: string
                description: ClusterDataPlaneLabels is a set of labels that will be
                  applied to the Konnect DataPlane.
                type: object
              controlPlaneRef:
                description: ControlPlaneRef is a reference to a ControlPlane this
                  DataPlaneKonnectExtension is associated with.
                properties:
                  konnectID:
                    description: |-
                      KonnectID is the schema for the KonnectID type.
                      This field is required when the Type is konnectID.
                    type: string
                  konnectNamespacedRef:
                    description: |-
                      KonnectNamespacedRef is a reference to a Konnect Control Plane entity inside the cluster.
                      It contains the name of the Konnect Control Plane.
                      This field is required when the Type is konnectNamespacedRef.
                    properties:
                      name:
                        description: Name is the name of the Konnect Control Plane.
                        type: string
                    required:
                    - name
                    type: object
                  type:
                    description: |-
                      Type can be one of:
                      - konnectID
                      - konnectNamespacedRef
                    enum:
                    - konnectID
                    - konnectNamespacedRef
                    type: string
                type: object
                x-kubernetes-validations:
                - message: when type is konnectNamespacedRef, konnectNamespacedRef
                    must be set
                  rule: 'self.type == ''konnectNamespacedRef'' ? has(self.konnectNamespacedRef)
                    : true'
                - message: when type is konnectID, konnectID must be set
                  rule: 'self.type == ''konnectID'' ? has(self.konnectID) : true'
              controlPlaneRegion:
                description: ControlPlaneRegion is the region of the Konnect Control
                  Plane.
                type: string
              serverURL:
                description: ServerURL is the URL of the Konnect server.
                type: string
            required:
            - clusterCertificateSecretName
            - controlPlaneRef
            - controlPlaneRegion
            - serverURL
            type: object
          status:
            description: Status is the status of the DataPlaneKonnectExtension resource.
            properties:
              dataPlaneRefs:
                description: |-
                  DataPlaneRefs is the array  of DataPlane references this is associated with.
                  A new reference is set by the operator when this extension is associated with
                  a DataPlane through its extensions spec.
                items:
                  description: NamespacedRef is a reference to a namespaced resource.
                  properties:
                    name:
                      description: Name is the name of the referred resource.
                      maxLength: 253
                      minLength: 1
                      type: string
                    namespace:
                      description: |-
                        Namespace is the namespace of the referred resource.

                        For namespace-scoped resources if no Namespace is provided then the
                        namespace of the parent object MUST be used.

                        This field MUST not be set when referring to cluster-scoped resources.
                      type: string
                  required:
                  - name
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
