name: Reusable build

on:
  workflow_call:
    inputs:
      registry:
        description: Registry to use for image(s) naming and pushing.
        required: true
        type: string
      image-name:
        description: Image name to use for image(s) naming and pushing.
        required: true
        type: string

      push:
        description: Indicates whether to push the built image(s) to specified registry.
        required: true
        type: boolean
      file:
        description: The name of the Dockefile to use.
        required: false
        type: string
        default: Dockerfile
      target:
        description: The target to be built.
        required: false
        type: string
        default: distroless
      platforms:
        description: List of target platforms for build.
        required: true
        type: string
      outputs:
        description: Set outputs for docker/build-push-action.
        required: false
        type: string
      upload-artifact:
        description: |
          If a non empty string is provided then this will be used as path for
          artifact to upload, which will contain the built, exported container image.
          This artifact will be available for subsequent jobs under the name
          of "image".
        required: false
        type: string

    outputs:
      tags:
        value: ${{ jobs.build.outputs.tags }}
      version:
        value: ${{ jobs.build.outputs.version }}
      artifact:
        value: ${{ jobs.build.outputs.artifact }}
    
jobs:
  build:
    name: Build operator image(s)
    runs-on: ubuntu-latest

    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      version: ${{ steps.meta.outputs.version }}
      artifact: ${{ steps.set-artifact.outputs.artifact }}

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ${{ inputs.registry }}/${{ inputs.image-name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build image
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: ${{ inputs.push }}
          file: ${{ inputs.file }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: ${{ inputs.target }}
          platforms: ${{ inputs.platforms }}
          build-args: |
            TAG=${{ steps.meta.outputs.version }}
            COMMIT=${{ github.sha }}
            REPO_INFO=https://github.com/${{ github.repository }}.git
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: ${{ inputs.outputs }}

      - name: Upload artifact
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: ${{ inputs.upload-artifact }}

      - name: Set artifact output
        if: ${{ inputs.upload-artifact }}
        id: set-artifact
        run: echo "artifact=${{ inputs.upload-artifact }}" >> $GITHUB_OUTPUT
