name: cleanup

on:
  schedule:
    - cron: '8 */1 * * *' # Run once per hour
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  konnect:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: setup golang
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - name: cleanup orphaned test clusters
        run: go run ./hack/cleanup konnect
        env:
          KONG_TEST_KONNECT_ACCESS_TOKEN: ${{ secrets.KONG_TEST_KONNECT_ACCESS_TOKEN }}
          KONG_TEST_KONNECT_SERVER_URL: us.api.konghq.tech
          # Ref: https://github.com/Kong/sdk-konnect-go/issues/20
          KONG_CUSTOM_DOMAIN: konghq.tech
