name: falco-analyzed-e2e

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  MISE_VERBOSE: 1

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    outputs:
      falco_result: ${{ steps.falco_result.outcome }}
    steps:
    - name: start falco
      continue-on-error: true
      uses: falcosecurity/falco-actions/start@4a4ff48cca452b3b03f06073d1ae0ff564503fc9
      with:
        mode: analyze
    
    - name: checkout repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: go.mod

    - name: build docker image
      env:
        IMG: kong-operator
        TAG: e2e-${{ github.sha }}
      run: make docker.build

    - uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
      with:
        install: false

    - name: run e2e tests
      run: make test.e2e
      env:
        KONG_TEST_KONG_OPERATOR_IMAGE_LOAD: kong-operator:e2e-${{ github.sha }}
        GOTESTSUM_JUNITFILE: "e2e-tests.xml"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: upload diagnostics
      if: always()
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: diagnostics-e2e
        path: /tmp/ktf-diag*
        if-no-files-found: ignore

    - name: stop falco and upload results
      id: falco_result
      continue-on-error: true
      uses: falcosecurity/falco-actions/stop@4a4ff48cca452b3b03f06073d1ae0ff564503fc9
      with:
        mode: analyze
  
  analyze_falco_results:
    name: Analyze Falco Results
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: run-e2e
    if: contains(needs.run-e2e.result, 'success') && needs.run-e2e.outputs.falco_result == 'success'
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Analyze Falco Results
        uses: falcosecurity/falco-actions/analyze@4a4ff48cca452b3b03f06073d1ae0ff564503fc9
        continue-on-error: true
